columnSuffix: null
contentColumnType: string
fieldGroup: e8409ecf-0e2a-4845-b6ad-1b2f31d3cf21 # Drinks
handle: drinkImage
instructions: ''
name: 'Drink Image'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:8959d0fa-e78a-4440-8c4f-27e6dfebe549' # Drinks
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: ''
  selectionLabel: 'Add a drink image'
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:8959d0fa-e78a-4440-8c4f-27e6dfebe549' # Drinks
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:8959d0fa-e78a-4440-8c4f-27e6dfebe549' # Drinks
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
