defaultPlacement: end
enableVersioning: true
handle: homepage
name: Homepage
propagationMethod: all
siteSettings:
  0c0d8a39-b687-42d2-a010-ed1161827ba8: # Craft Coffee
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
